In [336]:
# 1. Loading data into pandas

In [337]:
import pandas as pd

In [338]:
data = pd.read_csv("linkdin_Job_data.csv")

In [339]:
# 2. Check first and last 5 rows.

In [340]:
data.head(5)

,job_ID,job,location,company_id,company_name,work_type,full_time_remote,no_of_employ,no_of_application,posted_day_ago,alumni,Hiring_person,linkedin_followers,hiring_person_link,job_details
0,3471657636,"Data Analyst, Trilogy (Remote) - $60,000/year USD","Delhi, Delhi, India",NaN,Crossover,Remote,Full-time · Associate,"1,001-5,000 employees · IT Services and IT Con...",200,8 hours,12 company alumni,NaN,"5,395,547 followers",NaN,About the job Crossover is the world's #1 sour...
1,3471669068,"Data Analyst, Trilogy (Remote) - $60,000/year USD","New Delhi, Delhi, India",NaN,Crossover,Remote,Full-time · Associate,"1,001-5,000 employees · IT Services and IT Con...",184,8 hours,12 company alumni,NaN,"5,395,547 followers",NaN,About the job Crossover is the world's #1 sour...
2,3474349934,Data Analyst - WFH,Greater Bengaluru Area,NaN,Uplers,Remote,Full-time · Mid-Senior level,"1,001-5,000 employees · IT Services and IT Con...",200,9 hours,3 company alumni,Shahid Ahmad,NaN,https://www.linkedin.com/in/shahid-ahmad-a2613...,About the job Profile: ML EngineersExperience:...
3,3472816027,Data Analyst,"Gurugram, Haryana, India",NaN,PVAR SERVICES,On-site,Full-time,1-10 employees,200,7 hours,NaN,Vartika Singh,"2,094 followers",https://www.linkedin.com/in/vartika-singh-,About the job Designation: Data AnalystLocatio...
4,3473311511,Data Analyst,"Mohali district, Punjab, India",NaN,Timeline Freight Brokers,On-site,Full-time,1-10 employees,8,26 minutes,1 company alumni,Manisha (Gisele Smith),NaN,https://www.linkedin.com/in/manisharathore0029,About the job The ideal candidate will use the...

In [341]:
data.tail(5)

,job_ID,job,location,company_id,company_name,work_type,full_time_remote,no_of_employ,no_of_application,posted_day_ago,alumni,Hiring_person,linkedin_followers,hiring_person_link,job_details
7922,3472039871,Back End Developer,"Kochi, Kerala, India",NaN,Orion Innovation,Hybrid,Full-time · Associate,"5,001-10,000 employees · IT Services and IT Co...",25,2 days,24 company alumni,Poornima Viswanathan,NaN,https://www.linkedin.com/in/poornima-viswanath...,About the job The ideal candidate will show in...
7923,3473194471,Software Engineer - Senior,"Gurugram, Haryana, India",NaN,Uplers,On-site,Full-time · Mid-Senior level,"1,001-5,000 employees · IT Services and IT Con...",18,2 days,3 company alumni,Tejveer Singh,NaN,https://www.linkedin.com/in/tejveer-singh-a348...,About the job Experience: 4 - 8 yearsProfile: ...
7924,3461005032,Vue JS,"Hyderabad, Telangana, India",NaN,Tata Consultancy Services,On-site,Full-time · Mid-Senior level,"10,001+ employees · IT Services and IT Consulting",15,6 days,"10,080 company alumni",ANNIE ANTONY,"11,923,634 followers",https://www.linkedin.com/in/annie-antony-a1041...,About the job Role- Vue js DeveloperExperience...
7925,3474305684,iOS Developer,"Bengaluru, Karnataka, India",NaN,Uplers,Remote,Full-time · Mid-Senior level,"1,001-5,000 employees · IT Services and IT Con...",17,1 day,3 company alumni,Arjun Jaggi,NaN,https://www.linkedin.com/in/arjunjaggi7,About the job Profile: iOS DeveloperExperience...
7926,3459352801,Power train function developer,"Bengaluru, Karnataka, India",NaN,Akkodis,Hybrid,Full-time · Mid-Senior level,"10,001+ employees · IT Services and IT Consulting",43,1 week,27 company alumni,NaN,"1,421,090 followers",NaN,About the job JD Powertrain Function Developer...

In [342]:
# 4. Information of data

In [343]:
data.info

<bound method DataFrame.info of           job_ID                                                job  \
0     3471657636  Data Analyst, Trilogy (Remote) - $60,000/year USD
1     3471669068  Data Analyst, Trilogy (Remote) - $60,000/year USD
2     3474349934                                 Data Analyst - WFH
3     3472816027                                       Data Analyst
4     3473311511                                       Data Analyst
...          ...                                                ...
7922  3472039871                                 Back End Developer
7923  3473194471                         Software Engineer - Senior
7924  3461005032                                             Vue JS
7925  3474305684                                      iOS Developer
7926  3459352801                     Power train function developer

                            location  company_id               company_name  \
0                Delhi, Delhi, India         NaN                  Crossover
1            New Delhi, Delhi, India         NaN                  Crossover
2             Greater Bengaluru Area         NaN                     Uplers
3           Gurugram, Haryana, India         NaN              PVAR SERVICES
4     Mohali district, Punjab, India         NaN   Timeline Freight Brokers
...                              ...         ...                        ...
7922            Kochi, Kerala, India         NaN           Orion Innovation
7923        Gurugram, Haryana, India         NaN                     Uplers
7924     Hyderabad, Telangana, India         NaN  Tata Consultancy Services
7925     Bengaluru, Karnataka, India         NaN                     Uplers
7926     Bengaluru, Karnataka, India         NaN                    Akkodis

     work_type              full_time_remote  \
0       Remote         Full-time · Associate
1       Remote         Full-time · Associate
2       Remote  Full-time · Mid-Senior level
3      On-site                     Full-time
4      On-site                     Full-time
...        ...                           ...
7922    Hybrid         Full-time · Associate
7923   On-site  Full-time · Mid-Senior level
7924   On-site  Full-time · Mid-Senior level
7925    Remote  Full-time · Mid-Senior level
7926    Hybrid  Full-time · Mid-Senior level

                                           no_of_employ no_of_application  \
0     1,001-5,000 employees · IT Services and IT Con...               200
1     1,001-5,000 employees · IT Services and IT Con...               184
2     1,001-5,000 employees · IT Services and IT Con...               200
3                                        1-10 employees               200
4                                        1-10 employees                 8
...                                                 ...               ...
7922  5,001-10,000 employees · IT Services and IT Co...                25
7923  1,001-5,000 employees · IT Services and IT Con...                18
7924  10,001+ employees · IT Services and IT Consulting                15
7925  1,001-5,000 employees · IT Services and IT Con...                17
7926  10,001+ employees · IT Services and IT Consulting                43

     posted_day_ago                 alumni           Hiring_person  \
0           8 hours      12 company alumni                     NaN
1           8 hours      12 company alumni                     NaN
2           9 hours       3 company alumni            Shahid Ahmad
3           7 hours                    NaN           Vartika Singh
4        26 minutes       1 company alumni  Manisha (Gisele Smith)
...             ...                    ...                     ...
7922         2 days      24 company alumni    Poornima Viswanathan
7923         2 days       3 company alumni           Tejveer Singh
7924         6 days  10,080 company alumni            ANNIE ANTONY
7925          1 day       3 company alumni             Arjun Jaggi
7926         1 week      27 company alumni                     NaN

        linkedin_followers                                 hiring_person_link  \
0      5,395,547 followers                                                NaN
1      5,395,547 followers                                                NaN
2                      NaN  https://www.linkedin.com/in/shahid-ahmad-a2613...
3          2,094 followers         https://www.linkedin.com/in/vartika-singh-
4                      NaN     https://www.linkedin.com/in/manisharathore0029
...                    ...                                                ...
7922                   NaN  https://www.linkedin.com/in/poornima-viswanath...
7923                   NaN  https://www.linkedin.com/in/tejveer-singh-a348...
7924  11,923,634 followers  https://www.linkedin.com/in/annie-antony-a1041...
7925                   NaN            https://www.linkedin.com/in/arjunjaggi7
7926   1,421,090 followers                                                NaN

                                            job_details
0     About the job Crossover is the world's #1 sour...
1     About the job Crossover is the world's #1 sour...
2     About the job Profile: ML EngineersExperience:...
3     About the job Designation: Data AnalystLocatio...
4     About the job The ideal candidate will use the...
...                                                 ...
7922  About the job The ideal candidate will show in...
7923  About the job Experience: 4 - 8 yearsProfile: ...
7924  About the job Role- Vue js DeveloperExperience...
7925  About the job Profile: iOS DeveloperExperience...
7926  About the job JD Powertrain Function Developer...

[7927 rows x 15 columns]>

In [344]:
# 5. Checking Nan values

In [345]:
data.isna().sum()

job_ID                   0
job                     33
location                33
company_id            7927
company_name            35
work_type              191
full_time_remote        79
no_of_employ           324
no_of_application       40
posted_day_ago           7
alumni                3069
Hiring_person         2207
linkedin_followers    3113
hiring_person_link    2207
job_details             46
dtype: int64

In [346]:
# 6. Total rows and columns

In [347]:
data.shape

(7927, 15)

In [348]:
# 7. Removing duplicates

In [349]:
data.duplicated().value_counts()

False    7848
True       79
Name: count, dtype: int64

In [350]:
data.drop_duplicates(inplace = True)

In [351]:
data.duplicated().sum()

np.int64(0)

In [352]:
data.shape

(7848, 15)

In [353]:
data

,job_ID,job,location,company_id,company_name,work_type,full_time_remote,no_of_employ,no_of_application,posted_day_ago,alumni,Hiring_person,linkedin_followers,hiring_person_link,job_details
0,3471657636,"Data Analyst, Trilogy (Remote) - $60,000/year USD","Delhi, Delhi, India",NaN,Crossover,Remote,Full-time · Associate,"1,001-5,000 employees · IT Services and IT Con...",200,8 hours,12 company alumni,NaN,"5,395,547 followers",NaN,About the job Crossover is the world's #1 sour...
1,3471669068,"Data Analyst, Trilogy (Remote) - $60,000/year USD","New Delhi, Delhi, India",NaN,Crossover,Remote,Full-time · Associate,"1,001-5,000 employees · IT Services and IT Con...",184,8 hours,12 company alumni,NaN,"5,395,547 followers",NaN,About the job Crossover is the world's #1 sour...
2,3474349934,Data Analyst - WFH,Greater Bengaluru Area,NaN,Uplers,Remote,Full-time · Mid-Senior level,"1,001-5,000 employees · IT Services and IT Con...",200,9 hours,3 company alumni,Shahid Ahmad,NaN,https://www.linkedin.com/in/shahid-ahmad-a2613...,About the job Profile: ML EngineersExperience:...
3,3472816027,Data Analyst,"Gurugram, Haryana, India",NaN,PVAR SERVICES,On-site,Full-time,1-10 employees,200,7 hours,NaN,Vartika Singh,"2,094 followers",https://www.linkedin.com/in/vartika-singh-,About the job Designation: Data AnalystLocatio...
4,3473311511,Data Analyst,"Mohali district, Punjab, India",NaN,Timeline Freight Brokers,On-site,Full-time,1-10 employees,8,26 minutes,1 company alumni,Manisha (Gisele Smith),NaN,https://www.linkedin.com/in/manisharathore0029,About the job The ideal candidate will use the...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7922,3472039871,Back End Developer,"Kochi, Kerala, India",NaN,Orion Innovation,Hybrid,Full-time · Associate,"5,001-10,000 employees · IT Services and IT Co...",25,2 days,24 company alumni,Poornima Viswanathan,NaN,https://www.linkedin.com/in/poornima-viswanath...,About the job The ideal candidate will show in...
7923,3473194471,Software Engineer - Senior,"Gurugram, Haryana, India",NaN,Uplers,On-site,Full-time · Mid-Senior level,"1,001-5,000 employees · IT Services and IT Con...",18,2 days,3 company alumni,Tejveer Singh,NaN,https://www.linkedin.com/in/tejveer-singh-a348...,About the job Experience: 4 - 8 yearsProfile: ...
7924,3461005032,Vue JS,"Hyderabad, Telangana, India",NaN,Tata Consultancy Services,On-site,Full-time · Mid-Senior level,"10,001+ employees · IT Services and IT Consulting",15,6 days,"10,080 company alumni",ANNIE ANTONY,"11,923,634 followers",https://www.linkedin.com/in/annie-antony-a1041...,About the job Role- Vue js DeveloperExperience...
7925,3474305684,iOS Developer,"Bengaluru, Karnataka, India",NaN,Uplers,Remote,Full-time · Mid-Senior level,"1,001-5,000 employees · IT Services and IT Con...",17,1 day,3 company alumni,Arjun Jaggi,NaN,https://www.linkedin.com/in/arjunjaggi7,About the job Profile: iOS DeveloperExperience...
7926,3459352801,Power train function developer,"Bengaluru, Karnataka, India",NaN,Akkodis,Hybrid,Full-time · Mid-Senior level,"10,001+ employees · IT Services and IT Consulting",43,1 week,27 company alumni,NaN,"1,421,090 followers",NaN,About the job JD Powertrain Function Developer...

In [354]:
# 8. Assign a unique numerical identifier to each company in the 'company_ID' column and add it in a 'company_id' column based on the company's order of appearance in the DataFrame.

In [355]:
labels, _ = pd.factorize(data['company_name'])
data['company_id'] = labels + 1

In [356]:
data.head(3)

,job_ID,job,location,company_id,company_name,work_type,full_time_remote,no_of_employ,no_of_application,posted_day_ago,alumni,Hiring_person,linkedin_followers,hiring_person_link,job_details
0,3471657636,"Data Analyst, Trilogy (Remote) - $60,000/year USD","Delhi, Delhi, India",1,Crossover,Remote,Full-time · Associate,"1,001-5,000 employees · IT Services and IT Con...",200,8 hours,12 company alumni,NaN,"5,395,547 followers",NaN,About the job Crossover is the world's #1 sour...
1,3471669068,"Data Analyst, Trilogy (Remote) - $60,000/year USD","New Delhi, Delhi, India",1,Crossover,Remote,Full-time · Associate,"1,001-5,000 employees · IT Services and IT Con...",184,8 hours,12 company alumni,NaN,"5,395,547 followers",NaN,About the job Crossover is the world's #1 sour...
2,3474349934,Data Analyst - WFH,Greater Bengaluru Area,2,Uplers,Remote,Full-time · Mid-Senior level,"1,001-5,000 employees · IT Services and IT Con...",200,9 hours,3 company alumni,Shahid Ahmad,NaN,https://www.linkedin.com/in/shahid-ahmad-a2613...,About the job Profile: ML EngineersExperience:...

In [357]:
# 9. Drop unneccessary columns

In [358]:
data.columns

Index(['job_ID', 'job', 'location', 'company_id', 'company_name', 'work_type',
       'full_time_remote', 'no_of_employ', 'no_of_application',
       'posted_day_ago', 'alumni', 'Hiring_person', 'linkedin_followers',
       'hiring_person_link', 'job_details'],
      dtype='str')

In [359]:
columns_to_drop = ['alumni', 'hiring_person_link']
columns_to_keep = ['job_ID', 'job', 'location', 'company_id', 'company_name', 'work_type',
       'full_time_remote', 'no_of_employ', 'no_of_application',
       'posted_day_ago','Hiring_person', 'linkedin_followers', 'job_details']

In [360]:
columns_to_keep

['job_ID',
 'job',
 'location',
 'company_id',
 'company_name',
 'work_type',
 'full_time_remote',
 'no_of_employ',
 'no_of_application',
 'posted_day_ago',
 'Hiring_person',
 'linkedin_followers',
 'job_details']

In [361]:
len(columns_to_keep)

13

In [362]:
data = data[columns_to_keep]

In [363]:
data

,job_ID,job,location,company_id,company_name,work_type,full_time_remote,no_of_employ,no_of_application,posted_day_ago,Hiring_person,linkedin_followers,job_details
0,3471657636,"Data Analyst, Trilogy (Remote) - $60,000/year USD","Delhi, Delhi, India",1,Crossover,Remote,Full-time · Associate,"1,001-5,000 employees · IT Services and IT Con...",200,8 hours,NaN,"5,395,547 followers",About the job Crossover is the world's #1 sour...
1,3471669068,"Data Analyst, Trilogy (Remote) - $60,000/year USD","New Delhi, Delhi, India",1,Crossover,Remote,Full-time · Associate,"1,001-5,000 employees · IT Services and IT Con...",184,8 hours,NaN,"5,395,547 followers",About the job Crossover is the world's #1 sour...
2,3474349934,Data Analyst - WFH,Greater Bengaluru Area,2,Uplers,Remote,Full-time · Mid-Senior level,"1,001-5,000 employees · IT Services and IT Con...",200,9 hours,Shahid Ahmad,NaN,About the job Profile: ML EngineersExperience:...
3,3472816027,Data Analyst,"Gurugram, Haryana, India",3,PVAR SERVICES,On-site,Full-time,1-10 employees,200,7 hours,Vartika Singh,"2,094 followers",About the job Designation: Data AnalystLocatio...
4,3473311511,Data Analyst,"Mohali district, Punjab, India",4,Timeline Freight Brokers,On-site,Full-time,1-10 employees,8,26 minutes,Manisha (Gisele Smith),NaN,About the job The ideal candidate will use the...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7922,3472039871,Back End Developer,"Kochi, Kerala, India",105,Orion Innovation,Hybrid,Full-time · Associate,"5,001-10,000 employees · IT Services and IT Co...",25,2 days,Poornima Viswanathan,NaN,About the job The ideal candidate will show in...
7923,3473194471,Software Engineer - Senior,"Gurugram, Haryana, India",2,Uplers,On-site,Full-time · Mid-Senior level,"1,001-5,000 employees · IT Services and IT Con...",18,2 days,Tejveer Singh,NaN,About the job Experience: 4 - 8 yearsProfile: ...
7924,3461005032,Vue JS,"Hyderabad, Telangana, India",22,Tata Consultancy Services,On-site,Full-time · Mid-Senior level,"10,001+ employees · IT Services and IT Consulting",15,6 days,ANNIE ANTONY,"11,923,634 followers",About the job Role- Vue js DeveloperExperience...
7925,3474305684,iOS Developer,"Bengaluru, Karnataka, India",2,Uplers,Remote,Full-time · Mid-Senior level,"1,001-5,000 employees · IT Services and IT Con...",17,1 day,Arjun Jaggi,NaN,About the job Profile: iOS DeveloperExperience...
7926,3459352801,Power train function developer,"Bengaluru, Karnataka, India",2495,Akkodis,Hybrid,Full-time · Mid-Senior level,"10,001+ employees · IT Services and IT Consulting",43,1 week,NaN,"1,421,090 followers",About the job JD Powertrain Function Developer...

In [364]:
# 10. checking Nan values

In [365]:
data.isna().sum()

job_ID                   0
job                     33
location                33
company_id               0
company_name            35
work_type              188
full_time_remote        79
no_of_employ           310
no_of_application       40
posted_day_ago           7
Hiring_person         2188
linkedin_followers    3078
job_details             46
dtype: int64

In [366]:
data.dropna(inplace= True)

In [367]:
data

,job_ID,job,location,company_id,company_name,work_type,full_time_remote,no_of_employ,no_of_application,posted_day_ago,Hiring_person,linkedin_followers,job_details
3,3472816027,Data Analyst,"Gurugram, Haryana, India",3,PVAR SERVICES,On-site,Full-time,1-10 employees,200,7 hours,Vartika Singh,"2,094 followers",About the job Designation: Data AnalystLocatio...
7,3472808738,Shopify Developer,"Delhi, India",6,Digital Impressions,On-site,Full-time,51-200 employees,2,7 hours,Rashmi Aggarwal,"1,045 followers",About the job The ideal candidate will be resp...
8,3475061559,Database Developer,"Gurugram, Haryana, India",7,Kline & Company,Hybrid,Full-time,201-500 employees,7,25 minutes,Duncan Lawie,"30,319 followers",About the job Are you an experienced Microsoft...
10,3471883751,Shopify Developer,"Noida, Uttar Pradesh, India",9,Unitalks Technologies,Remote,Full-time,11-50 employees,22,10 hours,Yamini Gupta,"4,780 followers",About the job Create an engaging and knowledge...
11,3467390929,Data Engineer,"Gurugram, Haryana, India",10,ReNew Power,On-site,Full-time · Mid-Senior level,"501-1,000 employees · Renewable Energy Semicon...",111,5 hours,Neha Yadav,"198,797 followers",About the job About the organizationFounded in...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7917,3466122931,LINUX DEVICE DRIVER DEVELOPER,"Bengaluru, Karnataka, India",2492,SmartSoC Solutions Pvt Ltd,On-site,Contract · Mid-Senior level,201-500 employees · Semiconductor Manufacturing,10,2 days,Benjamin Rajesh,"38,790 followers",About the job · The person should have an expe...
7918,3469629784,Senior Java Software Developer,"Pune, Maharashtra, India",2493,EPMware,Remote,Full-time,11-50 employees,99,4 days,Abhi Nerurkar,"2,354 followers",About the job EPMware is seeking a Senior Java...
7919,3471741258,AWS Cloud Specialist,"Hyderabad, Telangana, India",2494,Altvu,Hybrid,Full-time · Mid-Senior level,201-500 employees · Human Resources Services,52,3 days,SUNIL N,"13,280 followers",About the job Position: - AWS Cloud Specialist...
7920,3466165399,LTE Developer,"Hyderabad, Telangana, India",22,Tata Consultancy Services,Hybrid,Full-time,"10,001+ employees · IT Services and IT Consulting",45,1 day,Madhuri Mahajan,"11,923,632 followers","About the job Dear Candidate, Greetings from T..."
7924,3461005032,Vue JS,"Hyderabad, Telangana, India",22,Tata Consultancy Services,On-site,Full-time · Mid-Senior level,"10,001+ employees · IT Services and IT Consulting",15,6 days,ANNIE ANTONY,"11,923,634 followers",About the job Role- Vue js DeveloperExperience...

In [368]:
# 11 Cleaning individual columns

In [369]:
data.no_of_employ

3                                          1-10 employees
7                                        51-200 employees
8                                       201-500 employees
10                                        11-50 employees
11      501-1,000 employees · Renewable Energy Semicon...
                              ...
7917      201-500 employees · Semiconductor Manufacturing
7918                                      11-50 employees
7919         201-500 employees · Human Resources Services
7920    10,001+ employees · IT Services and IT Consulting
7924    10,001+ employees · IT Services and IT Consulting
Name: no_of_employ, Length: 3459, dtype: str

In [379]:
# Splitting the no. of employees and industry into 2 columns
data['no_of_employ'].str.split('·', n=1, expand = True).rename(columns = {0:'no_of_employees', 1:'industry'})

           no_of_employees                                       industry
3           1-10 employees                                            NaN
7         51-200 employees                                            NaN
8        201-500 employees                                            NaN
10         11-50 employees                                            NaN
11    501-1,000 employees    Renewable Energy Semiconductor Manufacturing
...                    ...                                            ...
7917    201-500 employees                     Semiconductor Manufacturing
7918       11-50 employees                                            NaN
7919    201-500 employees                        Human Resources Services
7920    10,001+ employees                   IT Services and IT Consulting
7924    10,001+ employees                   IT Services and IT Consulting

[3459 rows x 2 columns]

In [380]:
data [['no_of_employees', 'industry']] = data['no_of_employ'].str.split('·', n=1, expand = True)

In [381]:
data.columns

Index(['job_ID', 'job', 'location', 'company_id', 'company_name', 'work_type',
       'full_time_remote', 'no_of_employ', 'no_of_application',
       'posted_day_ago', 'Hiring_person', 'linkedin_followers', 'job_details',
       'no_of_employees', 'industry'],
      dtype='str')

In [382]:
data.drop(columns= ['no_of_employ'])

,job_ID,job,location,company_id,company_name,work_type,full_time_remote,no_of_application,posted_day_ago,Hiring_person,linkedin_followers,job_details,no_of_employees,industry
3,3472816027,Data Analyst,"Gurugram, Haryana, India",3,PVAR SERVICES,On-site,Full-time,200,7 hours,Vartika Singh,"2,094 followers",About the job Designation: Data AnalystLocatio...,1-10 employees,NaN
7,3472808738,Shopify Developer,"Delhi, India",6,Digital Impressions,On-site,Full-time,2,7 hours,Rashmi Aggarwal,"1,045 followers",About the job The ideal candidate will be resp...,51-200 employees,NaN
8,3475061559,Database Developer,"Gurugram, Haryana, India",7,Kline & Company,Hybrid,Full-time,7,25 minutes,Duncan Lawie,"30,319 followers",About the job Are you an experienced Microsoft...,201-500 employees,NaN
10,3471883751,Shopify Developer,"Noida, Uttar Pradesh, India",9,Unitalks Technologies,Remote,Full-time,22,10 hours,Yamini Gupta,"4,780 followers",About the job Create an engaging and knowledge...,11-50 employees,NaN
11,3467390929,Data Engineer,"Gurugram, Haryana, India",10,ReNew Power,On-site,Full-time · Mid-Senior level,111,5 hours,Neha Yadav,"198,797 followers",About the job About the organizationFounded in...,"501-1,000 employees",Renewable Energy Semiconductor Manufacturing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7917,3466122931,LINUX DEVICE DRIVER DEVELOPER,"Bengaluru, Karnataka, India",2492,SmartSoC Solutions Pvt Ltd,On-site,Contract · Mid-Senior level,10,2 days,Benjamin Rajesh,"38,790 followers",About the job · The person should have an expe...,201-500 employees,Semiconductor Manufacturing
7918,3469629784,Senior Java Software Developer,"Pune, Maharashtra, India",2493,EPMware,Remote,Full-time,99,4 days,Abhi Nerurkar,"2,354 followers",About the job EPMware is seeking a Senior Java...,11-50 employees,NaN
7919,3471741258,AWS Cloud Specialist,"Hyderabad, Telangana, India",2494,Altvu,Hybrid,Full-time · Mid-Senior level,52,3 days,SUNIL N,"13,280 followers",About the job Position: - AWS Cloud Specialist...,201-500 employees,Human Resources Services
7920,3466165399,LTE Developer,"Hyderabad, Telangana, India",22,Tata Consultancy Services,Hybrid,Full-time,45,1 day,Madhuri Mahajan,"11,923,632 followers","About the job Dear Candidate, Greetings from T...","10,001+ employees",IT Services and IT Consulting
7924,3461005032,Vue JS,"Hyderabad, Telangana, India",22,Tata Consultancy Services,On-site,Full-time · Mid-Senior level,15,6 days,ANNIE ANTONY,"11,923,634 followers",About the job Role- Vue js DeveloperExperience...,"10,001+ employees",IT Services and IT Consulting