In [153]:
import pandas as pd

In [154]:
pd.__version__

'3.0.1'

In [155]:
data = pd.read_csv("zomato.csv")

In [156]:
data.head(2)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari

In [157]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='str')

In [158]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  str
 1   address                      51717 non-null  str
 2   name                         51717 non-null  str
 3   online_order                 51717 non-null  str
 4   book_table                   51717 non-null  str
 5   rate                         43942 non-null  str
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  str
 8   location                     51696 non-null  str
 9   rest_type                    51490 non-null  str
 10  dish_liked                   23639 non-null  str
 11  cuisines                     51672 non-null  str
 12  approx_cost(for two people)  51371 non-null  str
 13  reviews_list                 51717 non-null  str
 14  menu_item                    51717 non-null  str
 15  listed_in(type)              51717 non-null  str
 16  listed_in(city)              51717 non-null  str
dtypes: int64(1), str(16)
memory usage: 6.7 MB

In [159]:
data.shape

(51717, 17)

In [160]:
columms_to_keep = ['name', 'online_order', 'book_table', 'rate','dish_liked','approx_cost(for two people)']
columns_to_drop = ['url', 'address','phone', 'location', 'rest_type','votes','cuisines','reviews_list', 'menu_item','listed_in(type)', 'listed_in(city)']

In [161]:
data.shape

(51717, 17)

In [162]:
len(columms_to_keep)

6

In [163]:
len(columns_to_drop)

11

In [164]:
# 1st way - filtering data

In [165]:
columms_to_keep

['name',
 'online_order',
 'book_table',
 'rate',
 'dish_liked',
 'approx_cost(for two people)']

In [166]:
modify_data = data[columms_to_keep]

In [167]:
modify_data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

In [168]:
# 2nd way, dropping columns

In [169]:
columms_to_keep

['name',
 'online_order',
 'book_table',
 'rate',
 'dish_liked',
 'approx_cost(for two people)']

In [170]:
data.drop(columns= columns_to_drop, inplace= True)

In [171]:
data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

In [172]:
# Renaming columns

In [173]:
# Removing 1 by 1

In [174]:
data.rename(columns ={"name":"name1"})

,name1,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

In [175]:
data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

In [176]:
data.columns

Index(['name', 'online_order', 'book_table', 'rate', 'dish_liked',
       'approx_cost(for two people)'],
      dtype='str')

In [177]:
data.columns[0].capitalize()

'Name'

In [178]:
for i in data.columns:
    print(i.capitalize())

Name
Online_order
Book_table
Rate
Dish_liked
Approx_cost(for two people)

In [179]:
new_column_names = []
for i in data.columns:
    new_column_names.append(i.capitalize())

In [180]:
new_column_names

['Name',
 'Online_order',
 'Book_table',
 'Rate',
 'Dish_liked',
 'Approx_cost(for two people)']

In [181]:
data.columns = new_column_names

In [182]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

In [183]:
# 3. Dropping duplicates

In [184]:
data.duplicated().value_counts()

True     32808
False    18909
Name: count, dtype: int64

In [185]:
data.drop_duplicates(inplace = True)

In [186]:
data.duplicated().sum()

np.int64(0)

In [187]:
# 4. Removing Nan values

In [188]:
data.isna().sum()

Name                               0
Online_order                       0
Book_table                         0
Rate                            2418
Dish_liked                     10587
Approx_cost(for two people)      140
dtype: int64

In [189]:
data.dropna(inplace = True)

In [190]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51611,Chung Wah,No,No,2.5 /5,Manchow Soup,800
51617,Breakfast House,No,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
51620,Fujian Express,Yes,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
51628,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
51677,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

In [191]:
data.reset_index(inplace= True)

In [192]:
data.drop(columns= "index", inplace=True)

In [193]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,No,No,2.5 /5,Manchow Soup,800
8246,Breakfast House,No,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,Yes,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

In [194]:
# 4. Cleaning individual columns

In [195]:
data["Rate"][14]

'3.9/5'

In [196]:
data["Rate"]

0        4.1/5
1        4.1/5
2        3.8/5
3        3.7/5
4        3.8/5
         ...
8245    2.5 /5
8246    3.6 /5
8247    3.8 /5
8248    4.2 /5
8249    2.5 /5
Name: Rate, Length: 8250, dtype: str

In [197]:
data["Rate"] = data["Rate"].str.replace(" ", "")

In [198]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,No,No,2.5/5,Manchow Soup,800
8246,Breakfast House,No,No,3.6/5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,Yes,No,3.8/5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2/5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,No,No,2.5/5,"Biryani, Andhra Meal",800

In [199]:
data["Rate"] = data["Rate"].str.replace("/"," out of ")

In [200]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1 out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1 out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8 out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7 out of 5,Masala Dosa,300
4,Grand Village,No,No,3.8 out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,No,No,2.5 out of 5,Manchow Soup,800
8246,Breakfast House,No,No,3.6 out of 5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,Yes,No,3.8 out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,No,No,2.5 out of 5,"Biryani, Andhra Meal",800

In [201]:
# 5. check for more transformations. Turn text columns into numerical columns.

In [202]:
data["Online_order"]

0       Yes
1       Yes
2       Yes
3        No
4        No
       ...
8245     No
8246     No
8247    Yes
8248     No
8249     No
Name: Online_order, Length: 8250, dtype: str

In [203]:
data["Online_order"] = data["Online_order"].apply(lambda x: 1 if x == "Yes" else 0)

In [204]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,1,Yes,4.1 out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,1,No,4.1 out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,1,No,3.8 out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,No,3.7 out of 5,Masala Dosa,300
4,Grand Village,0,No,3.8 out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,0,No,2.5 out of 5,Manchow Soup,800
8246,Breakfast House,0,No,3.6 out of 5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,1,No,3.8 out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,0,Yes,4.2 out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,0,No,2.5 out of 5,"Biryani, Andhra Meal",800

In [205]:
data.to_csv("Cleaned_csv_Zomato.csv")

In [206]:
pd.read_csv("Cleaned_csv_Zomato.csv")

,Unnamed: 0,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,0,Jalsa,1,Yes,4.1 out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,1,Spice Elephant,1,No,4.1 out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,2,San Churro Cafe,1,No,3.8 out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,3,Addhuri Udupi Bhojana,0,No,3.7 out of 5,Masala Dosa,300
4,4,Grand Village,0,No,3.8 out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...
8245,8245,Chung Wah,0,No,2.5 out of 5,Manchow Soup,800
8246,8246,Breakfast House,0,No,3.6 out of 5,"Coffee, Vada, Mla Dosa",300
8247,8247,Fujian Express,1,No,3.8 out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,8248,Nook - Aloft Bengaluru Cessna Business Park,0,Yes,4.2 out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,8249,Bhagini,0,No,2.5 out of 5,"Biryani, Andhra Meal",800

In [207]:
data.to_csv("Cleaned_csv_Zomato_no_index.csv", index = False)

In [208]:
pd.read_csv("Cleaned_csv_Zomato_no_index.csv")

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,1,Yes,4.1 out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,1,No,4.1 out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,1,No,3.8 out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,No,3.7 out of 5,Masala Dosa,300
4,Grand Village,0,No,3.8 out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,0,No,2.5 out of 5,Manchow Soup,800
8246,Breakfast House,0,No,3.6 out of 5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,1,No,3.8 out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,0,Yes,4.2 out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,0,No,2.5 out of 5,"Biryani, Andhra Meal",800